name: 'Deploy'
on: push

jobs:
  deploy:
    if: startsWith(github.repository, 'MelanX/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install'
        run: sudo apt-get install -y python3 python3-pip optipng

      - name: 'Configure'
        run: pip3 install mkdocs==1.2.3 mkdocs-material==8.2.5 mkdocs-git-revision-date-localized-plugin==1.0.1

      - name: 'Optimize Images'
        run: |
          find . -name "*.png" -exec optipng -o7 {} \;

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: 'Push images'
        with:
          commit_message: 'Optimize images'
          commit_user_email: 'info@melanx.de'

      - name: 'Create table of mods'
        run: python scripts/generate_table.py

      - name: 'Create WIP pages'
        run: python scripts/generate_missing_pages.py

      - name: 'Build Wiki'
        run: mkdocs build -d build_site

      - name: 'Deploy'
        uses: 'JamesIves/github-pages-deploy-action@4.1.4'
        with:
          branch: gh-pages
          folder: 'build_site'
          clean: true
          git-config-name: 'Github Actions'
          git-config-email: 'info@melanx.de'
