name: 'Deploy'
on: push

jobs:
  deploy:
    if: startsWith(github.repository, 'MelanX/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Cache'
        id: cache
        uses: actions/cache@v2
        with:
          path: .image_cache
          key: ${{ runner.os }}-image-cache-${{ hashFiles('**/*.png') }}

      - name: 'Install'
        run: sudo apt-get install -y python3 python3-pip optipng

      - name: 'Configure'
        run: pip3 install mkdocs==1.4.2 mkdocs-material==9.1.2

      - name: 'Optimize Images'
        run: |
          find . -name "*.png" -type f | while read -r file; do
            cache_file="$RUNNER_WORKSPACE/.image_cache/${file#./}"
            if [ ! -f "$cache_file" ] || [ "$file" -nt "$cache_file" ]; then
              mkdir -p "$(dirname "$cache_file")"
              optipng -o7 "$file"
              cp "$file" "$cache_file"
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: 'Push images'
        with:
          commit_message: 'Optimize images'
          commit_user_email: 'info@melanx.de'

      - name: 'Build Wiki'
        run: mkdocs build -d build_site

      - name: 'Modify pages'
        run: python modify_pages.py

      - name: 'Deploy'
        uses: 'JamesIves/github-pages-deploy-action@4.1.4'
        with:
          branch: gh-pages
          folder: 'build_site'
          clean: true
          git-config-name: 'Github Actions'
          git-config-email: 'info@melanx.de'

      - name: 'Save Cache'
        uses: actions/cache@v2
        with:
          path: .image_cache
          key: ${{ runner.os }}-image-cache-${{ hashFiles('**/*.png') }}
