name: 'Update Mods'
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/mod_pages_update.yml'
      - 'assets/**'
      - 'data/projects.json'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        run: sudo apt-get install -y python3

      - name: Update descriptions
        run: python scripts/descriptions/main.py ${{ secrets.MODRINTH_TOKEN }}
